swagger: "2.0"
info:
  title: Airline API
  description: A detailed description of the operation.
    Use markdown for rich text representation,
    such as **bold**, *italic*, and [links](https://swagger.io).
  version: 1.0.0
host: localhost:3000
schemes:
  - http
tags:
  - name: Seat
    description: Seats for a given model
securityDefinitions:
  OAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://example.com/oauth/authorize
    tokenUrl: https://example.com/oauth/token
paths:
  /seat/{model_id}:
    get:
      tags:
        - Seat
      summary: Get all seats in an airplane model
      parameters:
        - name: model_id
          in: path
          type: string
          required: true
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              success:
                type: boolean
              message:
                type: string
              data:
                type: array
                items:
                  type: object
                  properties:
                    seat_id:
                      type: number
                    model_id:
                      type: number
                    model_name:
                      type: string
                    seat_name:
                      type: string
                    class:
                      type: string
              token:
                type: string
        404:
          description: Not found
        401:
          description: Unauthorized
        502:
          description: Server Error


    post:
      tags:
        - Seat
      parameters:
        - name: model_id
          in: path
          type: string
          required: true
        - name: body
          in: body
          schema:
            type: object
            required:
              - model_id
              - seat_name
              - class
            properties:
              model_id:
                type: string
              seat_name:
                type: string
              class:
                type: string
      summary: Add new seat to the model
      responses:
        201:
          description: Created
        400:
          description: Bad request
        401:
          description: Unauthorized
        404:
          description: Not found
        502:
          description: Server Error


  /seat/{model_id}/{seat_id}:
    delete:
      parameters:
        - name: flight_id
          in: path
          type: integer
          required: true
        - name: seat_id
          in: path
          type: integer
          required: true
      tags:
        - Seat
      summary: Delete a seat
      responses:
        200:
          description: OK, deleted
        401:
          description: Unauthorized
        404:
          description: Seat not Found
        400:
          description: Bad request
        502:
          description: Server Error