swagger: "2.0"
tags:
  - name: Pilot
    description: Pilot add/remove
info:
  title: Airline API
  description: A detailed description of the operation.
    Use markdown for rich text representation,
    such as **bold**, *italic*, and [links](https://swagger.io).
  version: 1.0.0
host: localhost:3000
schemes:
  - http
paths:
  /pilot:
    get:
      summary: Get all Pilots
      tags:
        - Pilot
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              success:
                type: boolean
              message:
                type: string
              data:
                type: array
                items:
                  type: object
                  properties:
                    staff_id:
                      type: number
                    licence_id:
                      type: string
                    pilot_code:
                      type: string
                    name:
                      type: string
                    nic:
                      type: string
              token:
                type: string
        502:
          description: Internal Server Error
    post:
      summary: Add new Pilot
      tags:
        - Pilot
      consumes:
        - application/json
      parameters:
        - name: details
          in: body
          schema:
            type: object
            required:
              - name
              - nic
              - licence_id
              - pilot_code
            properties:
              name:
                type: string
              nic:
                type: string
              type:
                type: string
              licence_id:
                type: string
              pilot_code:
                type: string
      responses:
        201:
          description: Created
        400:
          description: Bad request
        502:
          description: Internal Server Error
  /pilot/{staff_id}:
    delete:
      summary: Remove a Pilot
      tags:
        - Pilot
      consumes:
        - application/json
      parameters:
        - name: staff_id
          in: path
          type: integer
          required: true
      responses:
        200:
          description: OK
        404:
          description: Not found
        502:
          description: Internal Server Error