swagger: "2.0"
tags:
  - name: Booking
    description: Booking management

info:
  title: Airline API
  description: A detailed description of the operation.
    Use markdown for rich text representation,
    such as **bold**, *italic*, and [links](https://swagger.io).
  version: 1.0.0
host: localhost:3000
schemes:
  - http
paths:
  /booking:
    get:
      summary: Get all bookings
      tags:
        - Booking
      responses:
        200:
          description: OK
        404:
          description: User not found
        401:
          description: Unauthorized
        502:
          description: Server Error


            