swagger: "2.0"
info:
  title: Airline API
  description: A detailed description of the operation.
    Use markdown for rich text representation,
    such as **bold**, *italic*, and [links](https://swagger.io).
  version: 1.0.0
host: localhost:3000
schemes:
  - http
tags:
  - name: Book Flight
    description: Flight Booking
securityDefinitions:
  OAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://example.com/oauth/authorize
    tokenUrl: https://example.com/oauth/token
paths:
  /book_flight/:
    get:
      tags:
        - Book Flight
      summary: Get All Flight booking by schedule id
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              success:
                type: boolean
              message:
                type: string
              data:
                type: array
                items:
                  type: object
                  properties:
                    schedule_id:
                      type: number
                    date:
                      type: string
                    flight_id:
                      type: string
                    dep_time:
                      type: string
                    arrival_time:
                      type: string
              token:
                type: string
        404:
          description: Not found
          schema:
            type: object
            items:
              type: object
              properties:
                success:
                  type: boolean
                message:
                  type: string
                data:
                  type: array
                token:
                  type: string
        502:
          description: Internal server error
  /book_flight/:id:
    get:
      tags:
        - Book Flight
      summary: Get flight booking by id
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              success:
                type: boolean
              message:
                type: string
              data:
                type: array
                items:
                  type: object
                  properties:
                    schedule_id:
                      type: number
                    date:
                      type: string
                    flight_id:
                      type: string
                    dep_time:
                      type: string
                    arrival_time:
                      type: string
              token:
                type: string
        404:
          description: Not found
          schema:
            type: object
            items:
              type: object
              properties:
                success:
                  type: boolean
                message:
                  type: string
                data:
                  type: array
                token:
                  type: string
        502:
          description: Internal server error


