swagger: "2.0"
tags:
  - name: Report
    description: Report generation

info:
  title: Airline API
  description: A detailed description of the operation.
    Use markdown for rich text representation,
    such as **bold**, *italic*, and [links](https://swagger.io).
  version: 1.0.0
host: localhost:3000
schemes:
  - http
paths:
  /path:
    get:
      responses:
        200:
          description:
          schema:
