swagger: "2.0"
tags:
  - name: Gate
    description: Gate
info:
  title: Airline API
  description: A detailed description of the operation.
    Use markdown for rich text representation,
    such as **bold**, *italic*, and [links](https://swagger.io).
  version: 1.0.0
host: localhost:3000
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: x-access-token
schemes:
  - http
paths:
  /gate/:
    get:
      security:
        - ApiKeyAuth: []
      summary: Get all gates
      tags:
        - Gate
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              success:
                type: boolean
              message:
                type: string
              data:
                type: array
                items:
                  type: object
                  properties:
                    gate_id:
                      type: number
                    gate_name:
                      type: number
                    airport_id:
                      type: string
                    airport_name:
                      type: string
              token:
                type: string
        502:
          description: Internal Server Error
    post:
      security:
        - ApiKeyAuth: []
      summary: Add new gate to an airport
      tags:
        - Gate
      consumes:
        - application/json
      parameters:
        - name: details
          in: body
          schema:
            type: object
            required:
              - name
              - airport_id
            properties:
              name:
                type: string
              airport_id:
                type: number
      responses:
        200:
          description: OK
        400:
          description: Bad request
        502:
          description: Internal Server Error
  /gate/{gate_id}:
    get:
      security:
        - ApiKeyAuth: []
      summary: Get gate by id
      tags:
        - Gate
      parameters:
        - name: gate_id
          in: path
          type: integer
          required: true
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              success:
                type: boolean
              message:
                type: string
              data:
                type: array
                items:
                  type: object
                  properties:
                    gate_id:
                      type: number
                    gate_name:
                      type: number
                    airport_id:
                      type: string
                    airport_name:
                      type: string
              token:
                type: string
        404:
          description: Not found
        502:
          description: Internal Server Error
    put:
      security:
        - ApiKeyAuth: []
      tags:
        - Gate
      summary: Update Gate
      consumes:
        - application/json
      parameters:
        - name: gate_id
          in: path
          type: integer
          required: true
        - name: details
          in: body
          schema:
            type: object
            required:
              - name
              - airport_id
            properties:
              name:
                type: string
              airport_id:
                type: number
      responses:
        200:
          description: OK, Updated
        404:
          description: Not found
        400:
          description: Bad Request
        502:
          description: Internal Server Error
    delete:
      security:
        - ApiKeyAuth: []
      tags:
        - Gate
      parameters:
        - name: gate_id
          in: path
          type: integer
          required: true
      summary: Delete a gate
      responses:
        200:
          description: OK, deleted
        404:
          description: Not found
        502:
          description: Internal Server Error